# reference: https://www.idnet.co.jp/column/page_187.html

services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=1337
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "1337"
    ports:
      - "127.0.0.1:1337:1337"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    env_file:
      - py3/.env
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
